create DATABASE  KMS_SALES
Select *From [KMS DATA]

ALTER TABLE [KMS DATA]
DROP CONSTRAINT pk_ROW_ID_ROW_ID

SELECT *FROM [KMS DATA]


ALTER TABLE [KMS DATA]
DROP COLUMN province

ALTER TABLE [KMS DATA]
DROP COLUMN [PRODUCT_CONTAINER], [PRODUCT_BASE_MARGIN]

ALTER TABLE [KMS DATA]
ALTER COLUMN [SHIPPING_COST] DECIMAL(18, 3)

ALTER TABLE [KMS DATA]
ALTER COLUMN [UNIT_PRICE] DECIMAL(18, 3)

ALTER TABLE [KMS DATA]
ALTER COLUMN [PROFIT] DECIMAL(18, 3)


------QUESTION 1-----------TOP SELLING PRODUCT CATEGORY-------------

SELECT PRODUCT_CATEGORY, SUM(SALES) AS TOTALSALES
FROM [KMS DATA]
GROUP BY PRODUCT_CATEGORY
ORDER BY TOTALSALES DESC

Select *From [KMS DATA]


------QUESTION 2A----------TOP 3 REGIONS--------------
SELECT TOP 3 REGION, SUM(SALES) AS TOTALSALES
FROM [KMS DATA]
GROUP BY REGION
ORDER BY TOTALSALES DESC

------QUESTION 2B---------BOTTOM 3 REGIONS----------

SELECT REGION, SUM(SALES) AS TOTALSALES
FROM [KMS DATA]
GROUP BY REGION
ORDER BY TOTALSALES ASC

------QUESTION 3-------TOTAL SALES OF APPLIANCE IN ONTARIO------

	Select *From [KMS DATA]
	WHERE  REGION = 'ONTARIO'

	SELECT DISTINCT Product_SUB_Category FROM [KMS DATA];


SELECT REGION, SUM(SALES) AS TOTAL_APPLIANCES_SALES
FROM [KMS DATA]
WHERE PRODUCT_SUB_CATEGORY = 'APPLIANCES'
	GROUP BY REGION
	ORDER BY TOTAL_APPLIANCES_SALES DESC

------VIEW JUST ONTARIO------

SELECT REGION, SUM(SALES) AS TOTAL_APPLIANCES_SALES
FROM [KMS DATA]
WHERE REGION = 'ONTARIO' AND 
	PRODUCT_SUB_CATEGORY = 'APPLIANCES'
	GROUP BY REGION
	ORDER BY TOTAL_APPLIANCES_SALES

	Select *From [KMS DATA]

------QUESTION 4-------ADVISE ON HOW TO INCREASE REVENUE FROM BOTTOM 10 CUSTOMERS------
SELECT 
    CUSTOMER_NAME,
    COUNT(DISTINCT ORDER_QUANTITY) AS TOTAL_ORDER,
    AVG(Sales) AS AVG_ORDER_VALUE,
    MAX(ORDER_PRIORITY) AS MAX_PRIORITY,
    CUSTOMER_SEGMENT,
    REGION
FROM 
    [KMS DATA]
WHERE 
    CUSTOMER_NAME IN (
        SELECT TOP 10 CUSTOMER_NAME
        FROM [KMS DATA]
        GROUP BY CUSTOMER_NAME
        ORDER BY SUM(SALES) ASC
    )
GROUP BY 
    CUSTOMER_NAME, CUSTOMER_SEGMENT, REGION
ORDER BY AVG_ORDER_VALUE ASC

----------USING TOTAL REVENUE---------

SELECT TOP 10 
    ORDER_QUANTITY,
    CUSTOMER_NAME,
    SUM(SALES) AS TOTAL_REVENUE
FROM 
    [KMS DATA]
GROUP BY 
    ORDER_QUANTITY, CUSTOMER_NAME
ORDER BY 
    TOTAL_REVENUE ASC;

------QUESTION 5----------KMS INCURRED THE MOST SHIPPING COST USING WHAT SHIPPING METHOD?-------------

SELECT SHIP_MODE, SUM(SHIPPING_COST) AS TOTAL_SHIPPING_COST
FROM [KMS DATA]
GROUP BY SHIP_MODE
ORDER BY (TOTAL_SHIPPING_COST) DESC

SELECT *
FROM [KMS DATA]
WHERE SHIPPING_COST = (
SELECT MAX(SHIPPING_COST)
FROM [KMS DATA]
)

SELECT *FROM [KMS DATA]

------QUESTION 6--------MOST VALUABLE CUSTOMER AND PRODUCT THEY PURCHASE------
SELECT DISTINCT CUSTOMER_NAME FROM [KMS DATA]

SELECT TOP 20 CUSTOMER_NAME AS MOST_VALUABLE_CUSTOMER, 
	SALES, ORDER_QUANTITY, 
	UNIT_PRICE, PRODUCT_NAME, 
	PRODUCT_CATEGORY, 
	PRODUCT_SUB_CATEGORY
FROM [KMS DATA]
ORDER BY SALES DESC

------QUESTION 7-------SMALL BUSINESS CUSTOMER WITH HIGHEST SALES------

SELECT TOP 1 
   SALES AS HIGHESTSALES, CUSTOMER_SEGMENT
FROM [KMS DATA]
WHERE CUSTOMER_SEGMENT = 'Small Business'
ORDER BY SALES DESC

SELECT *FROM [KMS DATA]

------QUESTION 8--------CORPORATE CUSTOMER WITH THE MOST NUMBER OF ORDERS FROM 2009 TO 2012------

SELECT 
	ORDER_QUANTITY AS HIGHEST_ORDER, CUSTOMER_SEGMENT, ORDER_DATE
	FROM [KMS DATA]
	WHERE 
	CUSTOMER_SEGMENT = 'CORPORATE'
	AND
	YEAR(ORDER_DATE) BETWEEN 2009 AND 2012
	ORDER BY ORDER_QUANTITY DESC

	SELECT TOP 1
	ORDER_QUANTITY AS HIGHEST_ORDER, CUSTOMER_SEGMENT, ORDER_DATE
	FROM [KMS DATA]
	WHERE 
	CUSTOMER_SEGMENT = 'CORPORATE'
	AND
	YEAR(ORDER_DATE) >=2009 AND  YEAR(ORDER_DATE) <=2012
	ORDER BY ORDER_QUANTITY DESC

SELECT *FROM [KMS DATA]

------QUESTION 9-----------MOST PROFITABLE CONSUMER CUSTOMER------------

SELECT TOP 1
 CUSTOMER_SEGMENT AS MOST_PROFITABLE_CONSUMER, PROFIT
FROM [KMS DATA]
WHERE CUSTOMER_SEGMENT = 'CONSUMER'
ORDER BY PROFIT DESC

------QUESTION 10------CUSTOMERS THAT RETURNED ITEMS AND THEIR SEGMENT----------

---------JOIN KMS DATA AND ORDER STATUS--------

SELECT *FROM ORDER_STATUS

SELECT *FROM [KMS DATA]

SELECT [KMS DATA].CUSTOMER_NAME, [KMS DATA].CUSTOMER_SEGMENT, ORDER_STATUS.[STATUS]
FROM [KMS DATA]
INNER JOIN ORDER_STATUS ON [KMS DATA].ORDER_ID =ORDER_STATUS.[ORDER_ID];


SELECT [KMS DATA].CUSTOMER_NAME, [KMS DATA].CUSTOMER_SEGMENT, ORDER_STATUS.[STATUS]
FROM [KMS DATA]
INNER JOIN ORDER_STATUS ON [KMS DATA].ORDER_ID =ORDER_STATUS.[ORDER_ID]
WHERE [STATUS] = 'RETURNED'

----------question 11---------DID COMPANY SPEND SHIPPPING COST BASED ON ORDER PRIORITY?-------

SELECT 
    ORDER_PRIORITY,
    SHIP_MODE,
    COUNT (*) NUMBER_OF_ORDERS,
    AVG(SHIPPING_COST) AS AVERAGE_SHIPPING_COST
FROM 
    [KMS DATA]
GROUP BY 
    ORDER_PRIORITY, SHIP_MODE
ORDER BY 
    ORDER_PRIORITY, SHIP_MODE;


SELECT 
    [order_priority], 
    [ship_mode],
    COUNT([order_id]) AS order_count,
    SUM(sales - profit) AS estimated_shipping_cost,
    AVG(DATEDIFF(DAY, [order_date], [ship_date])) AS avg_ship_days
FROM 
    [KMS DATA] 
GROUP BY 
    [order_priority], [ship_mode]
ORDER BY 
    [order_priority], [ship_mode]    Desc;

------------END--------------------------

